import x from "@xterm/headless";
const t = new x.Terminal({ allowProposedApi: true });
let out = "";
t.onData((d) => (out += d));
let q = "";
for (let m = 1; m <= 3000; m++) q += `\x1b[?${m}$p`;
for (let m = 1; m <= 30; m++) q += `\x1b[${m}$p`;
q += "\x1b[?u\x1b[>q\x1bP+q536d756c78\x1b\\";
await new Promise((r) => t.write(q, r));
const dec = [...out.matchAll(/\x1b\[\?(\d+);([1-3])\$y/g)].map((m) => +m[1]);
const ansi = [...out.matchAll(/\x1b\[(\d+);([1-3])\$y/g)].map((m) => +m[1]);
console.log("DEC", JSON.stringify(dec));
console.log("ANSI", JSON.stringify(ansi));
console.log("other replies", JSON.stringify(out.replace(/\x1b\[\??\d+;\d\$y/g, "")));
