[package]
name = "s14-mcp"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rmcp = { version = "3.5.0", features = ["server", "macros", "schemars", "transport-io", "transport-streamable-http-server", "transport-streamable-http-client-unix-socket", "transport-streamable-http-client-reqwest", "client", "transport-child-process"] }
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
schemars = "1"
anyhow = "1"
